export enum cacheKeyEnum {
  SCHOOLS = "schools",
  STUDENTS = "students",
  PROFILE = "profiles",
  PERIOD = "periods",
  USERS = "users",
  NOTES = "Notes",
  ACADEMIC_CYCLE = "academic_cycle",
  MEDIAS = "medias",
  EMPLOYEES = "employees",
  CLASSES = "classes",
  CLASS_PERIOD = "classPeriod",
  CLASS_STUDENT = "classStudent",
  SCHEDULE = "schedule",
  DISCIPLINE = "discipline",
}
